/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.luso;

import io.luso.ui.di.DaggerAppUiComponent;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) {
        Scene scene = DaggerAppUiComponent.builder().build().scene();
        primaryStage.setScene(scene);
        primaryStage.show();
        primaryStage.setTitle("Re7");
    }
}
