/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.luso;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        StackPane stackPane = new StackPane();
        primaryStage.setScene(new Scene(stackPane, 1024,768));
        primaryStage.show();
    }
}
